// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3MShkSB_hEYVljzAY7CEMGYusuJuBlo4',
    appId: '1:982968813521:web:e280e0642962f06848c2f0',
    messagingSenderId: '982968813521',
    projectId: 'frendy-app-project',
    authDomain: 'frendy-app-project.firebaseapp.com',
    storageBucket: 'frendy-app-project.firebasestorage.app',
    measurementId: 'G-38N7B57L9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdAYvSFl_qGyi4reCsYcR68cUzyhhrh_4',
    appId: '1:982968813521:android:786cc97b7317aec448c2f0',
    messagingSenderId: '982968813521',
    projectId: 'frendy-app-project',
    storageBucket: 'frendy-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMtF2zQhKZ4V3IW5qj8zaGJqvUFTXuGZs',
    appId: '1:982968813521:ios:5bbfc39ca6fdede148c2f0',
    messagingSenderId: '982968813521',
    projectId: 'frendy-app-project',
    storageBucket: 'frendy-app-project.firebasestorage.app',
    iosBundleId: 'com.example.matchingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMtF2zQhKZ4V3IW5qj8zaGJqvUFTXuGZs',
    appId: '1:982968813521:ios:5bbfc39ca6fdede148c2f0',
    messagingSenderId: '982968813521',
    projectId: 'frendy-app-project',
    storageBucket: 'frendy-app-project.firebasestorage.app',
    iosBundleId: 'com.example.matchingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3MShkSB_hEYVljzAY7CEMGYusuJuBlo4',
    appId: '1:982968813521:web:a064ca51ef8b25d748c2f0',
    messagingSenderId: '982968813521',
    projectId: 'frendy-app-project',
    authDomain: 'frendy-app-project.firebaseapp.com',
    storageBucket: 'frendy-app-project.firebasestorage.app',
    measurementId: 'G-NSEDD3BGTG',
  );

}